version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.9.7-management
    mem_limit: 300m
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
       - rabbit-network


networks:
  rabbit-network: